services:
  backend:
    build: .
    container_name: go-backend
    ports:
      - "8000:8000" # Adjust the port if your backend uses a different one
    volumes:
      - advent-data:/app/app/database # Mount the volume to persist only the SQLite DB
    networks:
      - app-network

volumes:
  advent-data:
networks:
  app-network:
    driver: bridge
