# Generated by Django 5.1.1 on 2024-10-08 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                ("solucion", models.TextField()),
                ("titulo", models.CharField(max_length=255)),
                ("fecha_desbloqueo", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solucion_propuesta", models.TextField()),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                ("correcta", models.BooleanField(default=False)),
                (
                    "problema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.problema"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
